// internal ip address to the container

@hostname = 127.0.0.1
@port = 3000
@host = {{hostname}}:{{port}}

@contentType = application/json

@apiname=users

# Add New User
POST http://{{host}}/{{apiname}}
Host: {{host}}
Content-Type: {{contentType}}

{
	"ID": 0,
	"FirstName": "Bob",
	"LastName": "Smith"
}